#EJERCICIO 2
#OPERACIONES DE CONJUNTOS CON LISTAS.
#ESCRIBA UN PROGRAMA QUE TENGA 2 LISTAS Y QUE A CONTINUACION CREE LAS SIGUIENTES LISTAS (EN LAS QUE NO DEBEN HABER REPETICION)

#1 LISTAS DE PALABRAS QUE APARECEN EN LAS LISTAS.
#2 LISTAS DE PALABRAS QUE APARECEN EN LA PRIMERA LISTA, PERO NO EN LA SEGUNDA.
#3 LISTAS DE PALABRAS QUE APARECEN EN LA SEGUNDA LISTA, PERO NO EN LA PRIMERA.
#4 LISTAS DE PALABRAS QUE APARECEN EN AMBAS LISTAS.

lista1 = [1, 2, 3, 4, 5, 4, 3, 2, 2, 1, 5]
print(lista1)
lista2 = [4, 5, 6, 7, 8, 4, 5, 6, 7, 7, 8]
print(lista2)

#SE ELIMINARAN LOS ELEMENTOS REPETIDOS DE AMBAS LISTAS CON CONJUNTOS.
conjunto1 = set(lista1)
conjunto2 = set(lista2)

union = list(conjunto1 | conjunto2) #SE CREA UNA VARIABLE NUEVA PARA NUESTRA UNION DE AMBOS CONJUNTOS
solo1 = list(conjunto1 - conjunto2) #SE MUESTRA SOLO EL CONJUNTO 1
solo2 = list(conjunto2 - conjunto1) #SE MUESTRA SOLO EL CONJUNTO 2
interseccion = list(conjunto1 & conjunto2) #AQUI SE MUESTRAN AMBAS LISTAS

print(f"LISTAS DE PALABRAS QUE APARECEN EN LAS LISTAS: {union}")
print(f"LISTAS DE PALABRAS QUE APARECEN EN LA PRIMERA LISTA, PERO NO EN LA SEGUNDA: {solo1}")
print(f"LISTAS DE PALABRAS QUE APARECEN EN LA SEGUNDA LISTA, PERO NO EN LA PRIMERA: {solo2}")
print(f"LISTAS DE PALABRAS QUE APARECEN EN AMBAS LISTAS: {interseccion}")