#EJERCICIO CLASE-1(Rangos)
#EJERCICIO 1
#ITERAR UN RANGO DE 0 A 10 E IMPRIMIR LOS NUMEROS DIVISIBLES ENTRE 3
#EJEMPLO DE EJECUCION: 0,3,6,9
print('RANGO DE 0 A 10 CON NUMEROS DIVISIBLES ENTRE 3')
for i in range(11):
	if i % 3 == 0:
		print(i)